name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_http_cache:
    path: ..
  flutter:
    sdk: flutter
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  signals: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.19.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
